#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Wireless-Road

START=19
STOP=21

USE_PROCD=1
NAME=canopend
PROG=/usr/sbin/canopend

run_canopend() {
    procd_open_instance
	procd_set_param command $PROG -i 1 -s /etc/ -c "local-/tmp/CO_command_socket" can0
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
    run_canopend
}
